import {StyleSheet, StatusBar} from 'react-native';

export const stylesInfoArea = StyleSheet.create({
  container: {
    flex: 1,
    flexDirection: 'column',
    backgroundColor: 'white',
    width: '100%',
    height: '100%',
  },
  imgArea: {
    marginTop: 70,
    position: 'relative',
    width: '100%',
    height: 200,
    //resizeMode: 'contain',
  },
  conteudo: {
    fontSize: 100,
    color: 'red',
  },
  h1: {
    position: 'relative',
    textAlign: 'center',
    fontSize: 20,
    fontFamily: 'Roboto',
    top: 0,
    width: '100%',
    marginTop: 10,
    //resizeMode: 'contain',
    paddingBottom: 10,
    borderBottomColor: '#23b5b5',
    borderBottomWidth: 2,
    fontWeight: 'bold',
    color: 'black',
  },
  sensorContainer: {
    width: '100%',
    borderColor: '#23b5b5',
  },
  scroll: {
    padding: 10,
    margin: 10,
  },
  conteudoScroll: {
    margin: 5,
    fontSize: 20,
    color: 'black',
  },
  tittle: {
    fontWeight: 'bold',
    fontSize: 20,
    color: 'black',
  },
  conteudoInfo: {
    marginLeft: 10,
    fontSize: 20,
    justifyContent: 'center',
    alignItems: 'center',
    alignContent: 'center',
    color: 'black',
  },
  conteudoScrollInfo: {
    margin: 5,
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    alignContent: 'center',
    flexDirection: 'row',
  },
  conteudoDoencasPragas: {
    width: 'auto',
    margin: 3,
    alignItems: 'center',
    alignContent: 'center',
    flexDirection: 'row',
    borderWidth: 5,
    borderRadius: 30,
    borderColor: 'black',
  },
  conteudoDoencasPragasVerde: {
    width: 'auto',
    margin: 3,
    alignItems: 'center',
    alignContent: 'center',
    flexDirection: 'row',
    borderWidth: 2,
    borderRadius: 30,
    borderColor: 'green',
  },
  conteudoDoencasPragasAmarelo: {
    width: 'auto',
    margin: 3,
    alignItems: 'center',
    alignContent: 'center',
    flexDirection: 'row',
    borderWidth: 2,
    borderRadius: 30,
    borderColor: '#dddd46',
  },
  conteudoDoencasPragasVermelho: {
    width: 'auto',
    margin: 3,
    alignItems: 'center',
    alignContent: 'center',
    flexDirection: 'row',
    borderWidth: 2,
    borderRadius: 30,
    borderColor: 'red',
  },
  simboloAlertaVermelho: {
    width: 20,
    height: 20,
    alignItems: 'center',
    alignContent: 'center',
    borderRadius: 10,
    backgroundColor: 'red',
    marginLeft: 15,
    marginRight: 10,
  },
  simboloAlertaAmarelo: {
    width: 20,
    height: 20,
    alignItems: 'center',
    alignContent: 'center',
    borderRadius: 10,
    backgroundColor: '#dddd46',
    marginLeft: 15,
    marginRight: 10,
  },
  simboloAlertaVerde: {
    width: 20,
    height: 20,
    alignItems: 'center',
    alignContent: 'center',
    borderRadius: 10,
    backgroundColor: 'green',
    marginLeft: 15,
    marginRight: 10,
  },
});
